### ISSUE TITLE
I get warning (Warning: componentWillReceiveProps has been renamed,) with latest React.  Maybe time to update?

### ISSUE THREAD

**Issue by felipecarrillo100** [arqex/react-datetime#671] opened 2019-12-12 01:07 UTC
I get a deprecate Warning: componentWillReceiveProps has been renamed,
I guess it is time to update before the method is completely removed from support.

These are the versions I use.
    "moment": "^2.24.0",
    "react-datetime": "^2.16.3",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",

And this is the warning I get:
react-dom.development.js?61bb:12357 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: DateTime

**Comment by jaagupku** [comment] 2019-12-16 09:13
Duplicate of #649

**Comment by arqex** [comment] 2020-09-20 13:46
Thanks for raising the issue, and sorry for the delay! It's fixed as part of version 3 🙂

**Closed by arqex** 2020-09-20 13:46 UTC
